name: 'Run OPA Policy on Terraform File'
description: 'Composite action to run OPA against a Terraform file using a local policy'
inputs:
  tf_plan_json:
    description: 'JSON Terraform plan file to evaluate'
    required: true
  policy_name:
    description: 'Name of the OPA policy to evaluate'
    required: true
    default: 'terraform'
  opa_version:
    description: 'Version of OPA to use'
    required: false
    default: 'latest'

runs:
  using: "composite"
  steps:
    - name: Setup OPA
      uses: open-policy-agent/setup-opa@v2
      with:
        version: ${{ inputs.opa_version }}

    - name: Run OPA Policy
      shell: bash
      run: |
        echo ${{ inputs.tf_plan_json }} > ./input.json
        opa eval --format pretty --input ./input.json --data "./${{ inputs.policy_name }}/" "data.terraform.deny"
      working-directory: ${{ github.action_path }}

    # Optionally, fail if policy denies
    - name: Fail if denied
      shell: bash
      run: |
        result=$(opa eval --format json --input ./input.json --data "./${{ inputs.policy_name }}/" "data.terraform.deny" | jq '.result[0].expressions[0].value')
        if [ "$result" != "[]" ]; then
          echo "OPA policy denied the Terraform file."
          exit 1
        fi
      working-directory: ${{ github.action_path }}